# Generated by Django 5.1.6 on 2025-02-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('ad_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, verbose_name='نوع آگهی')),
                ('property_type', models.CharField(choices=[('warehouse', 'سوله / سالن / خرپا'), ('office', 'اداری'), ('land', 'زمین / پارکینگ'), ('other', 'سایر')], max_length=20, verbose_name='نوع ملک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('land_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ زمین')),
                ('warehouse_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ سوله')),
                ('office_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ اداری')),
                ('building_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ بنا')),
                ('total_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ کل')),
                ('price_per_meter', models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ متری')),
                ('deposit', models.CharField(blank=True, max_length=50, null=True, verbose_name='ودیعه')),
                ('rent_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='اجاره')),
                ('has_crane', models.BooleanField(default=False, verbose_name='جرثقیل')),
                ('has_stage', models.BooleanField(default=False, verbose_name='سکو')),
                ('has_100amp', models.BooleanField(default=False, verbose_name='برق تا ۱۰۰ آمپر')),
                ('has_200amp', models.BooleanField(default=False, verbose_name='برق تا ۲۰۰ آمپر')),
                ('has_400amp', models.BooleanField(default=False, verbose_name='برق بالای ۴۰۰ آمپر')),
                ('in_complex', models.BooleanField(default=False, verbose_name='در مجموعه/شهرکی')),
                ('independent', models.BooleanField(default=False, verbose_name='مستقل')),
                ('on_road', models.BooleanField(default=False, verbose_name='بر جاده')),
                ('showroom', models.BooleanField(default=False, verbose_name='شوروم')),
                ('pharmaceutical', models.BooleanField(default=False, verbose_name='دارویی')),
                ('special_property', models.BooleanField(default=False, verbose_name='ملک ویژه')),
                ('automotive', models.BooleanField(default=False, verbose_name='خودرویی / نمایندگی')),
                ('location', models.CharField(choices=[('ghods', 'قدس(قلعه حسن خان)/ زاگرس'), ('garmdareh', 'گرمدره'), ('mosallas', 'ابتدای مخصوص تا ایرانخودرو'), ('magspecial', 'مخصوص / ایرانخودرو تا وردآورد'), ('magwardavard', 'مخصوص/ وردآورد تا کرج'), ('fathstart', 'ابتدای فتح تا آزادگان'), ('azadwardavard', 'آزادگان تا وردآورد'), ('ahmadabad', 'احمدآباد مستوفی'), ('danesh', 'شهرک دانش')], max_length=50, verbose_name='محل')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='تصویر آگهی')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate_website.property')),
            ],
        ),
    ]
