# Generated by Django 5.1.6 on 2025-02-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='بدون توضیح'),
        ),
    ]
