# Generated by Django 5.1.6 on 2025-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_website', '0005_property_available_property_rent_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.CharField(choices=[('has_crane', 'جرثقیل'), ('has_stage', 'سکو'), ('has_400amp', 'برق بالای ۴۰۰ آمپر')], default=1, max_length=50, verbose_name='محل'),
            preserve_default=False,
        ),
    ]
