# Generated by Django 5.1.6 on 2025-02-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_website', '0006_property_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='facilities',
        ),
    ]
